sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull blackchip/pac8

script:
  - docker run --mount type=bind,source="$(pwd)",target=/root/go/src/github.com/blackchip-org/rcs blackchip/pac8 /bin/bash -c "cd /root/go/src/github.com/blackchip-org/rcs ; go test ./..."
